PROJECT NAME: Cleaning Data ( LEVEL1, TASK3)
NAME: AMULA BLESSING PERESUWODE
CATEGORY: DATA ANALYTICS

In [4]:
import pandas as pd
import numpy as np

In [2]:
import os

folder = r"C:\Users\DELL\Desktop\task 3"

os.listdir(folder)

['Titanic-Dataset.csv']

In [5]:
file_path = r"C:\Users\DELL\Desktop\task 3\Titanic-Dataset.csv"

df = pd.read_csv(file_path)

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 891
Columns: 12

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [9]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [10]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [11]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [13]:
missing_report = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing Percentage": (df.isnull().mean() * 100).round(2)
})

missing_report = missing_report[missing_report["Missing Values"] > 0]

missing_report

          Missing Values  Missing Percentage
Age                  177               19.87
Cabin                687               77.10
Embarked               2                0.22

## Missing Data Handling Strategy

Missing values were assessed based on the proportion of missing data and the importance of each variable.

- Age: Missing age values will be replaced with the median age because age is a numerical variable and the median is less affected by extreme values than the mean.
- Embarked: The two missing values will be replaced with the mode because Embarked is a categorical variable and the mode represents the most common category.
- Cabin: Because a very large proportion of Cabin values are missing, direct statistical imputation would not be appropriate. The missing values will be represented as "Unknown" to preserve the records while clearly indicating that the cabin information was unavailable.

In [14]:
age_median = df["Age"].median()

df["Age"] = df["Age"].fillna(age_median)

print("Age median used for imputation:", age_median)
print("Remaining missing Age values:", df["Age"].isnull().sum())

Age median used for imputation: 28.0
Remaining missing Age values: 0

In [15]:
embarked_mode = df["Embarked"].mode()[0]

df["Embarked"] = df["Embarked"].fillna(embarked_mode)

print("Embarked mode used for imputation:", embarked_mode)
print("Remaining missing Embarked values:", df["Embarked"].isnull().sum())

Embarked mode used for imputation: S
Remaining missing Embarked values: 0

In [16]:
df["Cabin"] = df["Cabin"].fillna("Unknown")

print("Remaining missing Cabin values:", df["Cabin"].isnull().sum())

Remaining missing Cabin values: 0

In [18]:
duplicate_count = df.duplicated().sum()

print("Duplicate rows before cleaning:", duplicate_count)

Duplicate rows before cleaning: 0

In [19]:
df = df.drop_duplicates()

print("Duplicate rows after cleaning:", df.duplicated().sum())

Duplicate rows after cleaning: 0

In [20]:
print("Number of duplicate rows removed:", duplicate_count)

Number of duplicate rows removed: 0

## Duplicate Removal

Duplicate records were identified using all columns in the dataset. Exact duplicate rows were removed because they represent repeated records and could distort descriptive statistics and subsequent analysis. The number of duplicates removed was recorded to provide transparency in the cleaning process.

In [21]:
df["Sex"] = df["Sex"].str.strip().str.lower()

df["Sex"] = df["Sex"].replace({
    "m": "male",
    "f": "female"
})

df["Sex"] = df["Sex"].str.title()

df["Sex"].value_counts()

Sex
Male      577
Female    314
Name: count, dtype: int64

In [22]:
df["Embarked"] = df["Embarked"].str.strip().str.upper()

df["Embarked"].value_counts()

Embarked
S    646
C    168
Q     77
Name: count, dtype: int64

## Data Standardisation

Categorical variables were standardised to ensure consistent formatting. Leading and trailing spaces were removed, gender values were converted to a consistent title-case format, and embarkation codes were converted to uppercase. This reduces inconsistencies that could affect grouping and analysis.

In [23]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [24]:
df["PassengerId"] = df["PassengerId"].astype("string")
df["Survived"] = df["Survived"].astype("int64")
df["Pclass"] = df["Pclass"].astype("int64")
df["Age"] = df["Age"].astype("float64")
df["SibSp"] = df["SibSp"].astype("int64")
df["Parch"] = df["Parch"].astype("int64")
df["Fare"] = df["Fare"].astype("float64")
df["Name"] = df["Name"].astype("string")
df["Sex"] = df["Sex"].astype("string")
df["Ticket"] = df["Ticket"].astype("string")
df["Cabin"] = df["Cabin"].astype("string")
df["Embarked"] = df["Embarked"].astype("string")

In [25]:
df.dtypes

PassengerId     string
Survived         int64
Pclass           int64
Name            string
Sex             string
Age            float64
SibSp            int64
Parch            int64
Ticket          string
Fare           float64
Cabin           string
Embarked        string
dtype: object

## Data Type Correction

Data types were reviewed and corrected to ensure that each variable is stored in an appropriate format. Passenger IDs and text-based variables were stored as strings, while numerical variables such as Age and Fare were assigned numerical data types. Correct data types improve memory usage, calculations, filtering, and downstream analysis.

In [26]:
numeric_columns = df.select_dtypes(include=np.number).columns

print("Numerical columns:")
print(list(numeric_columns))

Numerical columns:
['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

In [27]:
outlier_report = []

for column in numeric_columns:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outliers = df[(df[column] < lower_bound) | (df[column] > upper_bound)]
    
    outlier_report.append({
        "Column": column,
        "Q1": Q1,
        "Q3": Q3,
        "IQR": IQR,
        "Lower Bound": lower_bound,
        "Upper Bound": upper_bound,
        "Outlier Count": len(outliers)
    })

outlier_report = pd.DataFrame(outlier_report)

outlier_report

     Column       Q1    Q3      IQR  Lower Bound  Upper Bound  Outlier Count
0  Survived   0.0000   1.0   1.0000       -1.500       2.5000              0
1    Pclass   2.0000   3.0   1.0000        0.500       4.5000              0
2       Age  22.0000  35.0  13.0000        2.500      54.5000             66
3     SibSp   0.0000   1.0   1.0000       -1.500       2.5000             46
4     Parch   0.0000   0.0   0.0000        0.000       0.0000            213
5      Fare   7.9104  31.0  23.0896      -26.724      65.6344            116

## Outlier Detection

The Interquartile Range (IQR) method was used to identify potential outliers in numerical variables. The IQR was calculated as the difference between the third quartile (Q3) and first quartile (Q1). Values below Q1 − 1.5 × IQR or above Q3 + 1.5 × IQR were flagged as potential outliers.

Outliers were reviewed before deciding whether to remove, cap, or retain them. Genuine extreme values were retained because removing valid observations could result in loss of useful information.

In [28]:
for column in numeric_columns:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outliers = df[
        (df[column] < lower_bound) |
        (df[column] > upper_bound)
    ]
    
    print(f"\n{column}: {len(outliers)} outliers")
    
    if len(outliers) > 0:
        print(outliers[column].head(10).to_list())

Survived: 0 outliers

Pclass: 0 outliers

Age: 66 outliers
[2.0, 58.0, 55.0, 2.0, 66.0, 65.0, 0.83, 59.0, 71.0, 70.5]

SibSp: 46 outliers
[3, 4, 3, 3, 4, 5, 3, 4, 5, 3]

Parch: 213 outliers
[1, 2, 1, 5, 1, 1, 5, 2, 2, 1]

Fare: 116 outliers
[71.2833, 263.0, 146.5208, 82.1708, 76.7292, 80.0, 83.475, 73.5, 263.0, 77.2875]

In [29]:
outlier_report

     Column       Q1    Q3      IQR  Lower Bound  Upper Bound  Outlier Count
0  Survived   0.0000   1.0   1.0000       -1.500       2.5000              0
1    Pclass   2.0000   3.0   1.0000        0.500       4.5000              0
2       Age  22.0000  35.0  13.0000        2.500      54.5000             66
3     SibSp   0.0000   1.0   1.0000       -1.500       2.5000             46
4     Parch   0.0000   0.0   0.0000        0.000       0.0000            213
5      Fare   7.9104  31.0  23.0896      -26.724      65.6344            116

In [30]:
print("Outliers will be retained because they may represent genuine passenger characteristics or fares.")

Outliers will be retained because they may represent genuine passenger characteristics or fares.

## Outlier Treatment Decision

The detected outliers were reviewed and retained because they may represent legitimate observations rather than data-entry errors. Removing these records could result in loss of meaningful information. Therefore, no observations were deleted or capped solely because they were identified as statistical outliers.

In [31]:
after_summary = {
    "Row Count": len(df),
    "Duplicate Count": df.duplicated().sum(),
    "Total Missing Values": df.isnull().sum().sum(),
    "Columns": len(df.columns)
}

after_summary

{'Row Count': 891,
 'Duplicate Count': np.int64(0),
 'Total Missing Values': np.int64(0),
 'Columns': 12}

In [32]:
before_rows = 891
before_duplicates = 0

before_missing = 866

In [33]:
summary = pd.DataFrame({
    "Metric": [
        "Row Count",
        "Duplicate Count",
        "Total Missing Values"
    ],
    "Before Cleaning": [
        before_rows,
        before_duplicates,
        before_missing
    ],
    "After Cleaning": [
        len(df),
        df.duplicated().sum(),
        df.isnull().sum().sum()
    ]
})

summary

                 Metric  Before Cleaning  After Cleaning
0             Row Count              891             891
1       Duplicate Count                0               0
2  Total Missing Values              866               0

In [34]:
print("Final data types:")
print(df.dtypes)

Final data types:
PassengerId     string
Survived         int64
Pclass           int64
Name            string
Sex             string
Age            float64
SibSp            int64
Parch            int64
Ticket          string
Fare           float64
Cabin           string
Embarked        string
dtype: object

In [35]:
print("Final missing values:", df.isnull().sum().sum())
print("Final duplicate rows:", df.duplicated().sum())
print("Final row count:", len(df))

Final missing values: 0
Final duplicate rows: 0
Final row count: 891

In [36]:
output_path = r"C:\Users\DELL\Desktop\task 3\titanic_cleaned.csv"

df.to_csv(output_path, index=False)

print("Cleaned dataset saved successfully!")
print(output_path)

Cleaned dataset saved successfully!
C:\Users\DELL\Desktop\task 3\titanic_cleaned.csv

In [46]:
dtype_summary = pd.DataFrame({
    "Column": df.columns,
    "Final Data Type": df.dtypes.astype(str).values
})

dtype_summary

         Column Final Data Type
0   PassengerId          string
1      Survived           int64
2        Pclass           int64
3          Name          string
4           Sex          string
5           Age         float64
6         SibSp           int64
7         Parch           int64
8        Ticket          string
9          Fare         float64
10        Cabin          string
11     Embarked          string

## Data Type Accuracy

After cleaning, each column was reviewed to ensure that its data type was appropriate for its intended use. Numerical variables were stored as numerical data types, while identifiers and categorical/text variables were stored as string types. This ensures that the dataset is suitable for accurate analysis and further processing.

In [39]:
import os

In [40]:
os.path.exists(output_path)

True

In [41]:
cleaned_df = pd.read_csv(output_path)

cleaned_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",Male,22.0,1,0,A/5 21171,7.2500,Unknown,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Female,26.0,0,0,STON/O2. 3101282,7.9250,Unknown,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",Male,35.0,0,0,373450,8.0500,Unknown,S

In [42]:
print("Rows:", cleaned_df.shape[0])
print("Columns:", cleaned_df.shape[1])
print("Missing values:", cleaned_df.isnull().sum().sum())
print("Duplicate rows:", cleaned_df.duplicated().sum())

Rows: 891
Columns: 12
Missing values: 0
Duplicate rows: 0

## Final Cleaning Summary

The dataset was systematically cleaned by assessing its initial data quality, handling missing values, removing duplicate records, standardising categorical variables, correcting data types, and detecting numerical outliers using the IQR method.

Missing Age values were replaced using the median, missing Embarked values were replaced using the mode, and missing Cabin values were labelled as "Unknown" to preserve the available records.

Duplicate records were identified and removed where applicable. Categorical values were standardised, and data types were corrected to ensure that each variable was stored appropriately.

Potential numerical outliers were identified using the IQR method and retained where they represented legitimate observations rather than confirmed data-entry errors.

Finally, the cleaned dataset was saved as a new CSV file named `titanic_cleaned.csv` for future analysis.